server:
  port: 8080

dotenv:
  enabled: true
  override: true

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: migration

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

  stripe:
    api:
      key: ${STRIPE_API_KEY}

  paypal:
    client:
      id: ${PAYPAL_CLIENT_ID}
      secret: ${PAYPAL_CLIENT_SECRET}
      method: ${PAYPAL_MODE}

  idram:
    api:
      url: ${IDRAM_API_URL}
      key: ${IDRAM_API_KEY}

  easypay:
    api:
      url: ${EASYPAY_API_URL}
      key: ${EASYPAY_API_KEY}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  header: ${JWT_HEADER}

logging:
  level:
    org.springframework.boot.context.properties: DEBUG